# Generated by Django 2.0.9 on 2018-12-06 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('picture', models.CharField(default='', max_length=1000)),
                ('front', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PieceInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('piece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TeraChess.Piece')),
            ],
        ),
        migrations.CreateModel(
            name='PieceSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pieceset',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TeraChess.Player'),
        ),
        migrations.AddField(
            model_name='pieceinstance',
            name='piece_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TeraChess.PieceSet'),
        ),
    ]
