# Generated by Django 2.0.9 on 2018-12-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeraChess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='password',
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(default='Enter Username Here', max_length=100),
        ),
    ]
