# Generated by Django 2.1.3 on 2018-12-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeraChess', '0003_auto_20181210_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='picture',
            new_name='picture_black',
        ),
        migrations.AddField(
            model_name='piece',
            name='picture_hite',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
